### ISSUE TITLE
Cypress e2e test fails from newly created project with vue cli and git-bash

### ISSUE THREAD

**Issue by marc-bouvier** [vuejs/vue-cli#2709]
### Version
3.0.5

### Node and OS info
node v8.9.3, npm 5.5.1,git-bash (Git version 2.19.1), Windows 7 

### Steps to reproduce
From git-bash in Windows.

Create a project with vue cli.

```
vue create hello-world
```

Use those vue-cli plugins : vue-router, vuex, sass, babel, eslint, unit-jest, e2e-cypress

```
cd hello-world
npm install
```

Run e2e test 

```
npx vue-cli-service test:e2e --headless
```

### What is expected?
Passing end to end from `tests/e2e/specs/test.js`

### What is actually happening?
```
$ npx vue-cli-service test:e2e --headless
npx: installed 1 in 1.447s
Path must be a string. Received undefined
D:\hello-world\node_modules\@vue\cli-service\bin\vue-cli-service.js
 INFO  Starting e2e tests...
 INFO  Starting development server...
 DONE  Compiled successfully in 7436ms 17:07:31
  App running at:
  - Local:   http://localhost:8080/
  - Network: http://10.70.5.181:8080/

  App is served in production mode.
  Note this is for preview or E2E testing only.

================================================================================
  (Run Starting)
  ┌────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:  3.1.0                                                            │
  │ Browser:  Electron 59 (headless)                                           │
  │ Specs:    1 found (test.js)                                                │
  └────────────────────────────────────────────────────────────────────────────┘
────────────────────────────────────────────────────────────────────────────────

  Running: test.js... (1 of 1)
(node:12836) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
 ERROR  Failed to compile with 1 errors17:07:45

 error 

Entry module not found: Error: Can't resolve 'D:\hello-world\tests\e2e\specs\integration\test.js' in 'D:\hello-world'
```

---
When I run cypress GUI I get the same issue. 

The configuration I get is the following :

```
{
animationDistanceThreshold: 5,
baseUrl: 'http://localhost:8080',
blacklistHosts: null,
chromeWebSecurity: true,
defaultCommandTimeout: 4000,
env: {},
execTimeout: 60000,
fileServerFolder: '',
fixturesFolder: 'tests/e2e/fixtures',
hosts: null,
integrationFolder: 'tests/e2e/specs',
modifyObstructiveCode: true,
numTestsKeptInMemory: 50,
pageLoadTimeout: 60000,
pluginsFile: 'tests/e2e/plugins/index.js',
port: null,
reporter: 'spec',
reporterOptions: null,
requestTimeout: 5000,
responseTimeout: 30000,
screenshotsFolder: 'tests/e2e/screenshots',
supportFile: 'tests/e2e/support/index.js',
taskTimeout: 60000,
testFiles: '**/*.*',
trashAssetsBeforeRuns: true,
userAgent: null,
video: true,
videoCompression: 32,
videoUploadOnPasses: true,
videosFolder: 'tests/e2e/videos',
viewportHeight: 660,
viewportWidth: 1000,
waitForAnimations: true,
watchForFileChanges: true
}
```

**Comment by SLMNBJ** [comment]
I have this error:

-  Running completion hooks...error: '@cypress/webpack-preprocessor' should be listed in the project's dependencies, not devDependencies (import/no-extraneous-dependencies) at vue-store-locator\tests\e2e\plugins\index.js:3:17:
  1 | // https://docs.cypress.io/guides/guides/plugins-guide.html
  2 | /* eslint-disable import/no-extraneous-dependencies global-require */
> 3 | const webpack = require('@cypress/webpack-preprocessor');
    |                 ^
  4 |
  5 | module.exports = (on, config) => {
  6 |   on('file:preprocessor', webpack({


error: Unexpected require() (global-require) at vue-store-locator\tests\e2e\plugins\index.js:7:21:
   5 | module.exports = (on, config) => {
   6 |   on('file:preprocessor', webpack({
>  7 |     webpackOptions: require('@vue/cli-service/webpack.config'),
     |                     ^
   8 |     watchOptions: {},
   9 |   }));
  10 |


error: '@vue/cli-service' should be listed in the project's dependencies, not devDependencies (import/no-extraneous-dependencies) at vue-store-locator\tests\e2e\plugins\index.js:7:21:
   5 | module.exports = (on, config) => {
   6 |   on('file:preprocessor', webpack({
>  7 |     webpackOptions: require('@vue/cli-service/webpack.config'),
     |                     ^
   8 |     watchOptions: {},
   9 |   }));
  10 |

**Comment by sodatea** [comment]
@SLMNBJ This is an unrelated issue. Caused by a missing comma in the generated file. Please manually add that comma to your file: https://github.com/vuejs/vue-cli/commit/4e90afe18980f0f288908a7f7ef0974dc5a4545f#diff-1c4d741ece51a603d9d28f55c9d1e306

**Comment by sodatea** [comment]
1. Why did you run this command using `npx`? `npm run test:e2e` should suffice.
2. Please update your `npm`. Could be this issue: https://github.com/zkat/npx/issues/144 which has been fixed in https://github.com/npm/npm/pull/19608 and shipped with [npm v5.8.0](https://github.com/npm/npm/releases/tag/v5.8.0)

**Comment by pixelart7** [comment]
I got this problem too, both headless and GUI. I ran it on Node 8.12.0, NPM 6.4.1, Yarn 1.10.1.

Output as a reference:
```
E:\Repositories\repo-name (master -> Github)
λ yarn test:e2e --headless
yarn run v1.10.1
$ vue-cli-service test:e2e --headless
 INFO  Starting e2e tests...
 INFO  Starting development server...


 WARNING  Compiled with 2 warnings                                                                                   18:48:20

 warning

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (350 KiB)
      js/chunk-vendors.19368321.js
      css/app.b7b6aaa9.css
      js/app.3e498f3d.js


 warning

webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/


  App running at:
  - Local:   http://localhost:8081/
  - Network: http://172.21.191.177:8081/

  App is served in production mode.
  Note this is for preview or E2E testing only.



====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    3.1.0                                                                              │
  │ Browser:    Electron 59 (headless)                                                             │
  │ Specs:      1 found (test.js)                                                                  │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running: test.js...                                                                      (1 of 1)
(node:38848) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
 ERROR  Failed to compile with 1 errors18:49:09

 error

Entry module not found: Error: Can't resolve 'E:\Repositories\repo-name\tests\e2e\specs\integration\test.js' in 'E:\Repositories\repo-name'
```

**Comment by marc-bouvier** [comment]
@sodatea I ran it with npx in order to use `--headless`

**Comment by marc-bouvier** [comment]
I upgraded to npm 6.4.1 and node 10.12.0 and still get the same result.

My guess would be that git-bash for windows might mess the path but I don't know enough of it's internal to actually try things about it.

By the way, I tried it on a linux machine and it works fine. But unfortunately, I can't use this machine yet for development purpose.

**Comment by sodatea** [comment]
@marc-bouvier You can also use `npm run test:e2e -- --headless`

**Comment by animagnam** [comment]
Am also getting this error on Windows 10, have run from git-bash and from within the Vue GUI, both times output is:
``` INFO  Starting e2e tests...
 INFO  Starting development server...


 DONE  Compiled successfully in 3481ms                                                                                                                                         8:39:39 PM

  App running at:
  - Local:   http://localhost:8081/
  - Network: http://192.168.0.104:8081/

  App is served in production mode.
  Note this is for preview or E2E testing only.


GET /__/ 200 82.174 ms - -
GET /__cypress/runner/cypress_runner.css 200 60.766 ms - -
GET /__cypress/runner/cypress_runner.js 200 348.245 ms - -
GET /__cypress/runner/fonts/fontawesome-webfont.woff2?v=4.7.0 200 2.777 ms - 77160
GET /__cypress/iframes/integration/test.js 200 12.117 ms - 709
(node:12908) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
 ERROR  Failed to compile with 1 errors20:39:57

 error

Entry module not found: Error: Can't resolve 'D:\project\tests\e2e\specs\integration\test.js' in 'D:\project\'
```

It seems to be adding an additional folder to the file path? `D:\project\tests\e2e\specs\integration\test.js` doesn't exist, `D:\project\tests\e2e\specs\test.js` does.

Here's my config:
```{
animationDistanceThreshold: 5,
baseUrl: 'http://localhost:8081',
blacklistHosts: null,
chromeWebSecurity: true,
defaultCommandTimeout: 4000,
env: {},
execTimeout: 60000,
fileServerFolder: '',
fixturesFolder: 'tests/e2e/fixtures',
hosts: null,
integrationFolder: 'tests/e2e/specs',
modifyObstructiveCode: true,
numTestsKeptInMemory: 50,
pageLoadTimeout: 60000,
pluginsFile: 'tests/e2e/plugins/index.js',
port: null,
reporter: 'spec',
reporterOptions: null,
requestTimeout: 5000,
responseTimeout: 30000,
screenshotsFolder: 'tests/e2e/screenshots',
supportFile: 'tests/e2e/support/index.js',
taskTimeout: 60000,
testFiles: '**/*.*',
trashAssetsBeforeRuns: true,
userAgent: null,
video: true,
videoCompression: 32,
videoUploadOnPasses: true,
videosFolder: 'tests/e2e/videos',
viewportHeight: 660,
viewportWidth: 1000,
waitForAnimations: true,
watchForFileChanges: true}
```

**Comment by sodatea** [comment]
Here's the complete debug logs of running the same project on both Windows & macOS:
https://gist.github.com/sodatea/ffd402ed21a32cb49448da3c886d212d

By searching `cypress:server:preprocessor getFile` we can see 3 matches in each log and it is the first one that's causing the error.

On Windows the output is
```
Mon, 15 Oct 2018 03:05:48 GMT cypress:server:socket watch test file 'integration\\test.js'
Mon, 15 Oct 2018 03:05:48 GMT cypress:server:socket will watch test file path 'tests\\e2e\\specs\\integration\\test.js'
Mon, 15 Oct 2018 03:05:48 GMT cypress:server:preprocessor getFile C:\Users\soda\test-vue-cli\hello-world\tests\e2e\specs\integration\test.js
```
Note that the second line, cypress did not replace the `integration\\` with empty string as expected (https://github.com/cypress-io/cypress/blob/93966e30db6fd1c7a2e7defdbfbb5127e06570f7/packages/server/lib/socket.coffee#L76).


So I think it's a duplicate of https://github.com/cypress-io/cypress/issues/712, which has been fixed in https://github.com/cypress-io/cypress/pull/2400 but not yet shipped.

**Comment by sodatea** [comment]
Fixed since cypress v3.1.1
