### ISSUE TITLE
Page auto-refreshing doesn't work in Brave

### ISSUE THREAD

**Issue by SilencerWeb** [vuejs/vue-cli#3507]
### Version
3.4.1

### Reproduction link
[https://github.com/SilencerWeb/gsap-training](https://github.com/SilencerWeb/gsap-training)

### Environment info
```
  System:
    OS: macOS 10.14.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  Binaries:
    Node: 11.7.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.8.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 72.0.3626.119
    Firefox: Not Found
    Safari: 12.0.2
  npmPackages:
    @ant-design/icons-vue:  1.0.1
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.2
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.2
    @vue/babel-preset-app:  3.4.1
    @vue/babel-preset-jsx:  1.0.0-beta.2
    @vue/babel-sugar-functional-vue:  1.0.0-beta.2
    @vue/babel-sugar-inject-h:  1.0.0-beta.2
    @vue/babel-sugar-v-model:  1.0.0-beta.2
    @vue/babel-sugar-v-on:  1.0.0-beta.2
    @vue/cli-overlay:  3.4.1
    @vue/cli-plugin-babel: ^3.4.0 => 3.4.1
    @vue/cli-plugin-eslint: ^3.4.0 => 3.4.1
    @vue/cli-service: ^3.4.0 => 3.4.1
    @vue/cli-shared-utils:  3.4.1
    @vue/component-compiler-utils:  2.6.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    ant-design-vue: ^1.3.5 => 1.3.5
    babel-helper-vue-jsx-merge-props:  2.0.3
    eslint-plugin-vue: ^5.0.0 => 5.2.2
    vue: ^2.6.6 => 2.6.7
    vue-eslint-parser:  5.0.0
    vue-hot-reload-api:  2.3.3
    vue-loader: ^15.6.4 => 15.6.4
    vue-ref:  1.0.4
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.21 => 2.6.7
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
Just clone it, install dependencies, run it, open Brave and try to change any file.

### What is expected?
Page auto-refreshing is expected after a file change

### What is actually happening?
No page auto-refreshing. It works ok in Chrome.

**Comment by LinusBorg** [comment]
In case you are referring to hot Module Reloading, it works fine for me on Brave (Mac) with your repository (once I fixed the missing module error).

**Comment by SilencerWeb** [comment]
@LinusBorg what module error?

**Comment by LinusBorg** [comment]
The one from the missing HelloWorld component. You just fixed it with this commit: https://github.com/SilencerWeb/gsap-training/commit/1e3fc8358c002b52e170d28e011b10f68e2cc5fe

**Comment by SilencerWeb** [comment]
@LinusBorg it still doesn't work :(

It doesn't work in another project too. Any clues why it could be like that?

**Comment by LinusBorg** [comment]
Hard to say, as I can't reproduce it.

**Comment by SilencerWeb** [comment]
@LinusBorg Same thing in Safari. Even more, if you reload the page, no changes will arrive. Same thing on iOS in any browser.
