### ISSUE TITLE
We're sorry but work doesn't work properly without JavaScript enabled. 

### ISSUE THREAD

**Issue by alien-neko** [vuejs/vue-cli#5470]
### Version
4.3.1

### Environment info
```
We're sorry but work doesn't work properly without JavaScript enabled. Please enable it to continue.
```

### Steps to reproduce
I created a VueJS app and I'm getting the following error when I look at the source code in the web browse

We're sorry but work doesn't work properly without JavaScript enabled. Please enable it to continue.

### What is expected?
Vue running smoothly

### What is actually happening?
Nothing

**Comment by sodatea** [comment]
It's expected. The `Preview` panel will try to render HTML but it does not run JavaScript so it only shows the content of the `<noscript>` tag.

The full source code is shown in the `Response` tab.

**Comment by babak-karimi-asl** [comment]
i also have this problem when building for production , blank page with this error in response tab .

**Comment by elizavetaanisimova** [comment]
I have the same problem, Xcode
Asks to enable javascript, how can I enable it?

**Comment by babak-karimi-asl** [comment]
my problem solved by changing vue instantiation in main.js with the following code : 
```javascript
new Vue({
    router,
    store,
    render: h => h(App)
}).$mount('#app');
```
one of my colleagues did this i don't know from where.

**Comment by kennyj2016** [comment]
I had mine resolved. It was due to a CORS policy setting. You may want to check your server's CORS policy setting. For Django, it needs following to be set in the settings.py if CORs module is installed.
CORS_ALLOW_ALL_ORIGINS = True

For Apache httpd, it maybe setup in the .htaccess like such:
Header always set Access-Control-Allow-Origin *

Other servers may have different syntax or configurations.

**Comment by actforjason** [comment]
https://github.com/vuejs/vue-cli/issues/5470#issuecomment-669112550
It worked in my case！

**Comment by Rastra17** [comment]
> 

Thank you for your solution to this problem. Your method worked in my case which was using Django as backend and Vue.js as frontend.

**Comment by hktalent** [comment]
me  too, is a bug

```
<strong>We're sorry but platform_serve doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>
```
When I disable the browser JS from safari and then re enable JS,

And the message will stay here forever

**Comment by OMG-y** [comment]
When I use spring boot to access third-party interfaces（another local login service），It is a bug with " We're sorry but xxx doesn't work properly without JavaScript enabled. Please enable it to continue."  

it seems that resource is not got from third-party local service
![14D5632B](https://user-images.githubusercontent.com/71764657/175004448-0cbc55fc-89f6-44f7-a9f2-e105d93a07b3.png)

**Comment by alamhubb** [comment]
我用vue-cli创建一个新项目，直接进行build，访问dist/index.html， 就提示这个

**Comment by pickyouu** [comment]
+1
      <strong>We're sorry but app2 doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>
    http://localhost:8080/js/app.js net::ERR_CONNECTION_RESET

**Comment by CailynH** [comment]
I change "history" to "hash" in the router mode, then the bug is resolved

**Comment by ning2510** [comment]
> my problem solved by replacing vue instantiation code in main.js with the following :
> 
> ```js
> new Vue({
>     router,
>     store,
>     render: h => h(App)
> }).$mount('#app');
> ```
> 
> one of my colleagues did this i don't know from where.

If this method doesn't work for you, try adding the following to the vue.config.js file:
```js
const { defineConfig } = require('@vue/cli-service')
module.exports = defineConfig({
  ...
  publicPath: './',
  outputDir:'dist',
  assetsDir:'static'
})

```

**Comment by yanchenghust** [comment]
> I change "history" to "hash" in the router mode, then the bug is resolved

it works for me too!

**Comment by donxia** [comment]
my problem is vue versions with vuex versions is incompatible

**Comment by gocodersuresh** [comment]
the first command npm run build to run the vue.js app and it fails .
How this bug still exist why one one is resolving it its failing for the first hello world program
